### ISSUE TITLE
your cypress integration is not working

### ISSUE THREAD

**Issue by ryparker** [tolicodes/picklejs#6]
`ReferenceError: Cypress is not defined` when attempting to run via the getting started instructions.

**Comment by LaloMores** [comment]
Same. When adding custom commands (which is the first time I ever write "Cypress" in the code itself for the Cypress.Commands.add sentence.
The file I use is the default one that comes with the installation of cypress (cypress/support/commands.js])

`W20190911-21:28:06.330(-3)? (STDERR)   ReferenceError: Cypress is not defined
W20190911-21:28:06.330(-3)? (STDERR)     at commands.js (cypress/support/commands.js:1:1)
W20190911-21:28:06.330(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190911-21:28:06.330(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190911-21:28:06.330(-3)? (STDERR)     at require (packages/modules-runtime.js:258:21)`
